name: networks_tocantins
channels:
  - conda-forge
dependencies:
  - python=3.12
  - scipy
  - numpy
  - jupyter
  - seaborn
  - pygraphviz
  - networkx
  - lxml
  - pydot
  - pandas
  - scienceplots
  - matplotlib
  - powerlaw
  - ipykernel
  - pip:
      - matplotlib-venn==1.1.2
